#!/bin/bash
cd "${0%/*}"
OUT=../linux
mkdir $OUT 2> /dev/null
touch $OUT/__init__.py
python setup.py build
DEST=lib.linux*
DEST=$(ls -d build/${DEST} | tail -1)
cp ${DEST}/pxpcap.cpython-38-x86_64-linux-gnu.so .. && cp ${DEST}/pxpcap.cpython-38-x86_64-linux-gnu.so ${OUT}/pxpcap.so
